# Generated by Django 4.2.6 on 2024-05-08 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MANAGEMENT_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attachments', models.FileField(upload_to='project_assignments/')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MANAGEMENT_APP.userproject')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to='MANAGEMENT_APP.userprofile')),
            ],
        ),
    ]
