# Generated by Django 4.2.6 on 2024-05-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MANAGEMENT_APP', '0003_userprofile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
    ]
